#!/bin/bash

# ~/.osx
# One Time Machine Setup

# General UI/UX

scutil --set ComputerName "Littledubs"
scutil --set HostName "Littledubs"
scutil --set LocalHostName "Littledubs"

#disable menu bar transparency
defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool false

#always show scrollbars
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

#speed up mission control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

#expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

#disable automatic termination of inactive apps
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

#disable scroll animations
defaults write -g NSScrollAnimationEnabled -bool NO

#don’t show dashboard as a space
defaults write com.apple.dock "dashboard-in-overlay" -bool true

# Mouse, Trackpad, Keyboard

#disable 'natural' scrolling direction on trackpad
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# Finder

#show status bar
defaults write com.apple.finder ShowStatusBar -bool true

#unhide library
chflags nohidden ~/Library

# Safari

#enable debug menu
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
