set shell=/usr/local/bin/zsh

"basic formatting {         
	set cursorline
	set backspace=indent,eol,start
	set showmatch
	set mouse=a
	set number
	set nowrap
	set nohlsearch

	set timeoutlen=0 ttimeoutlen=0

	syntax on                           " Enable syntax highlighting
	filetype on                         " enable filetype specific plugins

	set noexpandtab
	set tabstop=4
	set shiftwidth=4
	set softtabstop=4

	colorscheme base16-tomorrow-night
	set encoding=utf-8  " necessary to show unicode glyphs

	" Store temporary files in a central spot
	set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
	set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
"}

"go specific stuff{
	let g:go_fmt_autosave = 1
	let g:go_fmt_command = "goimports"
	let g:go_metalinter_autosave_enabled = ['vet', 'golint']
	au FileType go set noexpandtab
	au FileType go set shiftwidth=4
	au FileType go set softtabstop=4
	au FileType go set tabstop=4
"}

"custom maps {
	nmap <S-Tab> <<
	imap <S-Tab> <Esc><<i

	nmap <C-a> ^
	nmap <C-e> $

	imap <C-a> <Esc>^i
	imap <C-e> <Esc>$i

	imap <C-Return> <CR><CR><C-o>k<TAB>

	nmap <Esc> :noh<Esc>
	imap <Esc> :noh<Esc>

	noremap <F4> :pclose<CR>
	noremap <F3> :set hlsearch!<CR>
"}

"nerdtree {
	nnoremap <C-h> :NERDTreeToggle<cr>
"}

"ctrl-p {
	set runtimepath^=~/.vim/bundle/ctrlp.vim
"}

"deoplete {
        let g:deoplete#enable_at_startup = 1
"}

