#env vars {
  export EDITOR="nvim"
  
  export WORKSPACE=$HOME/workspace
  export DOTFILES=$WORKSPACE/dotfiles

  export PATH=/usr/local/sbin:$PATH
  export PATH=/usr/local/bin:$PATH
  export PATH=$HOME/bin:$PATH
#}

# common aliases {
  alias vim="nvim"
  alias j="jump"
#}

# tmux aliases {
  alias attach="tmux attach -t work || tmux new-session -s work"
  alias detach="tmux detach"
#}

# kubectl aliases {
  alias k="kubectl"
  alias mk="microk8s kubectl"
#}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -s "$HOME/.zsecure" ]; then
    source $HOME/.zsecure
fi

if [ -s "$HOME/.zprofile_linux" ]; then
    source $HOME/.zprofile_linux
fi

if [ -s "$HOME/.zprofile_darwin" ]; then
    source $HOME/.zprofile_darwin
fi

function addsshkeys() {
    if [ -f "$HOME/.ssh/id_rsa" ]; then 
	    ssh-add $HOME/.ssh/id_rsa &> /dev/null
    fi
}

