HISTFILE=$HOME/.zsh-history
KEYTIMEOUT=1

export ZSH=$HOME/.zsh

plugins=(
	git 
	jump 
	osx
)
ZSH_THEME="wcharczuk"

source $ZSH/zsh_init.sh
source $HOME/.zprofile

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/wcharczuk/workspace/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/wcharczuk/workspace/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/Users/wcharczuk/workspace/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/wcharczuk/workspace/google-cloud-sdk/completion.zsh.inc'; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
