export ZSH=$HOME/.oh-my-zsh

plugins=(git)
ZSH_THEME="powerline"

# For the powerline theme but this may be disabled.
POWERLINE_DETECT_SSH="true"
POWERLINE_NO_BLANK_LINE="true"
POWERLINE_HIDE_HOST_NAME="true"

# User configuration
source $ZSH/oh-my-zsh.sh
source $HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.zprofile

HISTFILE=$HOME/.zsh-history
KEYTIMEOUT=1
