#! /bin/bash

# BASE
echo "Installing Base Packages (like git etc.)"
sudo apt-get -y install build-essential wget curl git

# NODE
echo "Installing Node"
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get -y install node-js=4.4.0
sudo npm install -g bower grunt grunt-cli

# MONGO
echo "Installing Mongo"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
if [ ! -f /etc/apt/sources.list/mongodb-org-3.2.list ]; then
	echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
else 
	echo "Already added mongo 3.2 sources, skipping."
fi
sudo apt-get update
sudo apt-get install -y mongodb-org=3.2.4 mongo-org-server=3.2.4 mongo-db-org-shell=3.2.4 mongodb-org-mongos=3.2.4 mongodb-org-tools=3.2.4

# REDIS
echo "Installing Redis"
sudo add-apt-repository ppa:chris-lea/redis-server
sudo apt-get update
sudo apt-get install -y redis-server
